In [97]:
import pandas as pd
import numpy as np
from itertools import combinations
csvfile = pd.read_csv("Database3.csv")
X = csvfile.iloc[:, ].values
features = csvfile.columns
d = len(features) # Number of dimensions
csvfile_a = pd.read_csv("Database3a - 6.csv")
answer = csvfile_a.iloc[:, ].values

In [98]:
# Preference Vector - Initial
snum = 0.0000001
preference_vector = np.repeat(snum, d)

# Algorithm to find top-k
distances = np.linalg.norm(X - preference_vector, axis = 1)
k = 6; 
top_k = distances.argsort()[:k]
X[top_k]

array([[1, 2, 2, 1, 1, 1, 1, 1, 1],
       [1, 1, 2, 2, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 2, 1, 1, 1, 1],
       [1, 1, 1, 1, 2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 2, 2, 1, 1],
       [2, 1, 1, 1, 1, 1, 2, 1, 1]], dtype=int64)

In [99]:
# Standardization
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(X[top_k])
np.mean(x), np.std(x) 

(5.3455182667137164e-17, 0.8819171036881969)

In [100]:
# Principal Component
from sklearn.decomposition import PCA
c = k - 1 # c < k 
pca_item = PCA(n_components = c)
principalComponents_item = pca_item.fit_transform(x)
principalComponents_item # k arrays with c 

array([[ 2.01151861, -1.71060671, -1.33030098, -0.65101818, -0.1846407 ],
       [ 1.81972644, -0.12621267,  0.99991999,  1.1764652 ,  0.43446024],
       [ 0.72653833,  1.83681938,  1.17866368, -0.52544702, -0.57696966],
       [-0.72653833,  1.83681938, -1.17866368, -0.52544702,  0.57696966],
       [-1.81972644, -0.12621267, -0.99991999,  1.1764652 , -0.43446024],
       [-2.01151861, -1.71060671,  1.33030098, -0.65101818,  0.1846407 ]])

In [101]:
# Return c items to the user
# vec2 = []
# for i in np.absolute(principalComponents_item).T:
#     ivec = []
#     base = i[0]
#     int1 = -1
#     int2 = 0
#     for j in i:
#         int1 += 1
#         if j >= base:
#             base = j
#             int2 = int1
#             ivec.append(int2)
    
#     for i in ivec[::-1]:
#         if i in vec2:
#             continue
#         else:
#             int2 = i
#     vec2.append(int2)
vec = np.argmax(principalComponents_item, axis = 0)
# vec = []
# for i in l:
#     vec.append(i)
list(vec)

[0, 2, 5, 4, 3]

In [102]:
def choice(items, top_k, k):
    for i in range(0, k):
        for j in items:
            if (np.array_equal(answer[i], top_k[j])):
                return j
    return False  

In [103]:
# def combination(lst, n):
#     l = []
#     for i in range(0, len(lst)):
#         m = lst[i]
#         remLst = lst[i + 1:]
#         for p in combination(remLst, n - 1):
#             l.append([m] + p)
#     return l
# def combination(vec):
#     for i, v1 in enumerate(vec):
#         for j in range(i + 1, len(vec)):
#             yield [v1, vec[j]]
def combinations(vec, n):
    if not n:
        return [[]]
    if not vec:
        return []
    head = [vec[0]]
    tail = vec[1:]
    new_comb = [head + lis for lis in combinations(tail, n - 1)]
    return new_comb + combinations(tail, n)

In [104]:
def user_items(comb, all_vecs, terminate):
    vec = []
    for i in comb:
        for j in all_vecs:
            if (np.array_equal(a, i) == False):
                vec = a
                all_vecs.append(vec)
                terminate = False
    return vec, all_vecs, terminate  

In [119]:
# combination(vec2, 2)
all_vecs = []
comb = list(combinations(list(vec), 3))
print(comb)
it = 0
for i in comb:    
    if (np.array_equal(pd.unique(i), i)):
        it += 1
    else:
        comb = np.delete(comb, it, 0)
print(comb)
terminate = True
vec2 = user_items(comb, all_vecs, terminate)
vec2

[[0, 2, 5], [0, 2, 4], [0, 2, 3], [0, 5, 4], [0, 5, 3], [0, 4, 3], [2, 5, 4], [2, 5, 3], [2, 4, 3], [5, 4, 3]]


[[0, 2, 5],
 [0, 2, 4],
 [0, 2, 3],
 [0, 5, 4],
 [0, 5, 3],
 [0, 4, 3],
 [2, 5, 4],
 [2, 5, 3],
 [2, 4, 3],
 [5, 4, 3]]

In [120]:
# Arbitrarily choose one of c (User Step)
vec_index = choice(vec2, X[top_k], k)
v = X[top_k][vec_index]
new_preference_vector = (preference_vector + v) / 2
new_preference_vector

array([], shape=(0, 6, 9), dtype=float64)

In [121]:
# New top-k
new_distances = np.linalg.norm(X - new_preference_vector, axis = 1)
k = 6; 
new_top_k = new_distances.argsort()[:k]
X[new_top_k], X[top_k]

ValueError: operands could not be broadcast together with shapes (9,9) (0,6,9) 

array([[3, 0],
       [0, 0]], dtype=int64)

In [50]:
l = np.argmax([[1, 2, 2], [1, 2, 3]], axis = 0)
vec = []
for i in l:
    vec.append(i)
for i in vec:
    if (np.array_equal(np.unique(i), i) == False):
        np.delete(vec, i)
print(vec)

0
0
1
[0, 0, 1]


In [65]:
vec = [[1, 1, 2], [1, 2, 3]]
int = 0
for i in vec:
    if (np.array_equal(np.unique(i), i)):
        int += 1
    else:
        vec = np.delete(vec, int, 0)
print(vec)

[[1 2 3]]
